learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'


urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/', views.other,name='other'),
    
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'Hello World','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-default">
      <div class="container">
        <ul class="nav navbar">
          <li class="navbar-brand"><a href="{% url 'index'%}">Brand</a></li>
          <li class="navbar-brand navbar-link"><a href="{% url 'basic_app:other' %}">Admin</a></li>
          <li class="navbar-brand navbar-link"><a href="{% url 'basic_app:relative'%}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

learning_templates/basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}
   {% block body_block %}
     <h1>welcome to index</h1>
     <h2>index page extended base</h2>
     <h1>{{ number|add:'909' }}</h1>
     <h1>{{ text|cut:'World' }}</h1>
     <!-- <h1>{{ number|add:'909' }}</h1>
     <h1>{{ text|upper }}</h1> -->
   {% endblock%}

learning_templates/basic_app/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}
   {% block body_block %}
     <h1>welcome to other</h1>
     <h2>other page extended base</h2>
   {% endblock%}

learning_templates/basic_app/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
       <h1>Welcome to other url templates</h1>
       <a href="{% url 'basic_app:other' %}">The Other page</a>
       <a href="{% url 'admin:index' %}">The index page page</a>
       <a href="{% url 'index' %}">The index page page</a>
  </body>
</html>